#!/usr/bin/env node
// Generate apps/web/src/types/artifact.ts from the repo-root schema.json.
// Run: `npm run gen:types` (from apps/web). Keeps frontend types in lockstep
// with the Rust schema without a Rust toolchain dependency in node_modules.

import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "..", "..", "..", "schema.json");
const outPath = resolve(here, "..", "src", "types", "artifact.ts");

const raw = JSON.parse(readFileSync(schemaPath, "utf8"));

const banner = `/**
 * AUTOGENERATED from /schema.json — do not hand-edit.
 * Regenerate: \`npm run gen:types\` in apps/web.
 */`;

const ts = await compile(raw, "Artifact", {
  bannerComment: banner,
  additionalProperties: false,
  style: { singleQuote: false },
});

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, ts, "utf8");
console.log(`wrote ${outPath}`);
